/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdbcc", 
        "on-background": "#e7e0ee", 
        "on-error": "#690005", 
        "tertiary-fixed-dim": "#ffb694", 
        primary: "#cfbcff", 
        "secondary-fixed-dim": "#cfbcff", 
        "inverse-surface": "#e7e0ee", 
        "inverse-primary": "#6d33e5", 
        surface: "#15121b", 
        "on-tertiary-fixed": "#351000", 
        "inverse-on-surface": "#322f39", 
        error: "#ffb4ab", 
        secondary: "#cfbcff", 
        "primary-fixed": "#e9ddff", 
        "on-tertiary-container": "#ffffff", 
        "surface-container": "#211e28", 
        outline: "#958ea1", 
        "surface-variant": "#37333d", 
        "surface-container-lowest": "#0f0d16", 
        "on-primary-container": "#ffffff", 
        background: "#15121b", 
        "error-container": "#93000a", 
        "primary-container": "#8652ff", 
        "surface-container-highest": "#37333d", 
        "on-secondary-fixed-variant": "#4e3986", 
        "on-surface-variant": "#cbc3d8", 
        "on-tertiary": "#571f00", 
        "on-error-container": "#ffdad6", 
        "surface-dim": "#15121b", 
        "on-primary-fixed-variant": "#5400cc", 
        "on-tertiary-fixed-variant": "#7b2f00", 
        "on-primary-fixed": "#22005d", 
        "secondary-container": "#513b89", 
        "secondary-fixed": "#e9ddff", 
        "outline-variant": "#494455", 
        "on-secondary-fixed": "#220359", 
        "on-primary": "#3a0092", 
        "surface-container-high": "#2c2832", 
        "on-secondary-container": "#c2acff", 
        "on-surface": "#e7e0ee", 
        "surface-tint": "#cfbcff", 
        "surface-bright": "#3b3742", 
        "primary-fixed-dim": "#cfbcff", 
        "on-secondary": "#37206e", 
        "surface-container-low": "#1d1a24", 
        tertiary: "#ffb694", 
        "tertiary-container": "#bc5b28"
      },
      borderRadius: {
        DEFAULT: "0.25rem", 
        lg: "0.5rem", 
        xl: "0.75rem", 
        full: "9999px"
      },
      spacing: {
        "2xl": "64px", 
        lg: "24px", 
        sm: "8px", 
        xs: "4px", 
        md: "16px", 
        "container-max": "1440px", 
        xl: "40px", 
        base: "4px", 
        gutter: "24px"
      },
      fontFamily: {
        display: ["Inter", "sans-serif"], 
        "label-caps": ["Work Sans", "sans-serif"], 
        h3: ["Inter", "sans-serif"], 
        h1: ["Inter", "sans-serif"], 
        "body-md": ["Inter", "sans-serif"], 
        h2: ["Inter", "sans-serif"], 
        "body-lg": ["Inter", "sans-serif"], 
        "mono-sm": ["Space Grotesk", "monospace"], 
        headline: ["Inter", "sans-serif"], 
        body: ["Inter", "sans-serif"], 
        label: ["Work Sans", "sans-serif"]
      },
      fontSize: {
        display: ["48px", {lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700"}], 
        "label-caps": ["12px", {lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600"}], 
        h3: ["18px", {lineHeight: "1.4", letterSpacing: "0", fontWeight: "600"}], 
        h1: ["32px", {lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600"}], 
        "body-md": ["14px", {lineHeight: "1.5", letterSpacing: "0", fontWeight: "400"}], 
        h2: ["24px", {lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600"}], 
        "body-lg": ["16px", {lineHeight: "1.6", letterSpacing: "0", fontWeight: "400"}], 
        "mono-sm": ["13px", {lineHeight: "1.5", letterSpacing: "0", fontWeight: "400"}]
      }
    },
  },
  plugins: [],
}
